version: '3.8'

services:
  postgres:
    image: postgres:16.1
    restart: always
    ports:
      - 5434:5432
    container_name: postgres_backend
    env_file:
      - ./backend/.env
    networks:
      - transcendance
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:

networks:
  transcendance:
    driver: bridge