export * from './Footer/Footer';
export * from './Header/Header';
export * from './Menu/Menu';
export * from './Home/Home';
export * from './Pong/Pong';
export * from './Chat/Chat'
export * from './Login/Login'
export * from './Profile/Profile'
export * from './Card'